config/routes.rb
Rails.application.routes.draw do
  
  resources :blog_rakings
  resources :blog_comments
  resources :blogs
  resources :ranking
  get 'users/show'
  root to: 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
  # devise_scope :user do  
  #   get '/users/sign_out' => 'devise/sessions#destroy'     
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    def index
        @blog = Blog.all
    end
    has_many :blog_comment, -> { order "created_at DESC"}
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
    belongs_to :user
end

app/models/blog_raking.rb
class BlogRaking < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs
         
  has_one_attached :avatar
  
  validates :name, presence: true
  validates :age, presence: true
  validates :birthday, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :birthday, :avatar]
        devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :birthday, :avatar]
      end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  before_action :set_blog_comment, only: [:show, :edit, :update, :destroy]

  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
  end

  # GET /blog_comments/new
  def new
    @blog_comment = BlogComment.new
  end

  # GET /blog_comments/1/edit
  def edit
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(blog_comment_params)

    respond_to do |format|
      if @blog_comment.save
        new_url = "/blogs/" + @blog_comment.blog_id.to_s
        # format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully created.' }
        format.html { redirect_to new_url, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_comment }
      else
        format.html { render :new }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_comments/1
  # PATCH/PUT /blog_comments/1.json
  def update
    respond_to do |format|
      if @blog_comment.update(blog_comment_params)
        new_url = "/blogs/" + @blog_comment.blog_id.to_s
        format.html { redirect_to new_url, notice: 'Blog comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_comment }
      else
        format.html { render :edit }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy
    @blog_comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_comments_url, notice: 'Blog comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_comment
      @blog_comment = BlogComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_comment_params
      params.require(:blog_comment).permit(:user_id, :blog_id, :comment)
    end
end

app/controllers/blog_rakings_controller.rb
class BlogRakingsController < ApplicationController
  # GET /blog_rakings
  # GET /blog_rakings.json
  def index
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog_comment = BlogComment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to root_path, notice: 'Blog was successfully created.' }
        format.json { render :home, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @blog_users = Blog.all
  end
  def index
    @raking = Blog.group(:user_id).count()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_rakings_helper.rb
module BlogRakingsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_comments/_form.html.erb
<%= form_with(model: blog_comment, local: true) do |form| %>
  <% if blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
        <% blog_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :blog_id %>
    <%= form.number_field :blog_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing Blog Comment</h1>

<%= render 'form', blog_comment: @blog_comment %>

<!--<%= link_to 'Show', @blog_comment %> |-->
<!--<%= link_to 'Back', blog_comments_path %>-->

app/views/blog_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Blog</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_comments.each do |blog_comment| %>
      <tr>
        <td><%= blog_comment.user_id %></td>
        <td><%= blog_comment.blog_id %></td>
        <td><%= blog_comment.comment %></td>
        <td><%= link_to 'Show', blog_comment %></td>
        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New Blog Comment</h1>

<%= render 'form', blog_comment: @blog_comment %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog_comment.user_id %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @blog_comment.blog_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @blog_comment.comment %>
</p>

<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Back to blog', controller: "blogs", action: "show", id: @blog_comment.blog_id %>

app/views/blog_rakings/_form.html.erb
<%= form_with(model: blog_raking, local: true) do |form| %>
  <% if blog_raking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_raking.errors.count, "error") %> prohibited this blog_raking from being saved:</h2>

      <ul>
        <% blog_raking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :blog_id %>
    <%= form.number_field :blog_id %>
  </div>

  <div class="field">
    <%= form.label :raking %>
    <%= form.number_field :raking %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_rakings/edit.html.erb
<h1>Editing Blog Raking</h1>

<%= render 'form', blog_raking: @blog_raking %>

<%= link_to 'Show', @blog_raking %> |
<%= link_to 'Back', blog_rakings_path %>

app/views/blog_rakings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Rakings</h1>

<table>
  

  <tbody>
<div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      <% User.all.each do |blog_rakings| %>
        <div class="post-preview">
          <% if current_user.id == blog_rakings.id %>
          <%= link_to Blog do %>
            <h2 class="post-title">
              <%= blog_rakings.name%>
            </h2>
            <% end %>
          <% else %>
            <h2 class="post-title">
              <%= blog_rakings.name%>
            </h2>
          <% end %>
        </div>
      <div class="col-lg-8 col-md-10 mx-auto">
        Blog quantity: <%= blog_rakings.blogs.count()%>
      </div>
      <% end %>
        <hr>
      </div>
    </div>
  </div>

  </tbody>
</table>

<br>

app/views/blog_rakings/new.html.erb
<h1>New Blog Raking</h1>

<%= render 'form', blog_raking: @blog_raking %>

<%= link_to 'Back', blog_rakings_path %>

app/views/blog_rakings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog_raking.user_id %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @blog_raking.blog_id %>
</p>

<p>
  <strong>Raking:</strong>
  <%= @blog_raking.raking %>
</p>

<%= link_to 'Edit', edit_blog_raking_path(@blog_raking) %> |
<%= link_to 'Back', blog_rakings_path %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', :back %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <% if blog.user_id == current_user.id %>
      <tr>
        <td><%= blog.user_id %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', :back %>

app/views/blogs/show.html.erb
<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<div class="col-sm-4">
    <div class="card bg-light mb-3" style="max-width: 40rem;">
      <div class="card-header"><h2>Comment</h2></div>
      <div class="card-body">
      <%= form_with(model: @blog_comment, local: true) do |form| %>
        <div class= "field">
          <%= form.text_area :comment, :class => "form-control" %>
          <%= form.hidden_field :blog_id, :value => @blog.id %>
          <%= form.hidden_field :user_id, :value => current_user.id %>
        </div>
        <div class="actions">
          <%= form.submit %>
        </div>
       <% end %>
       <h2>Comment List: </h2>
       <ul>
          <% @blog.blog_comment.each do |blog_comment|%>
              <p class="card-text">・<%= blog_comment.comment %> (<%= blog_comment.user.name %>)
              <% if current_user.id == blog_comment.user_id %>
                <a><%= link_to 'Edit', edit_blog_comment_path(blog_comment.id) %></a>
              <% end %></p>
          <% end %>
        </ul>
       </div>
    </div>
  </div>
</div>

<% if current_user.id == @blog.user.id %>
  <a><%= link_to 'Edit', edit_blog_path(@blog) %> |</a>
<% end %>
<%= link_to 'Back', root_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
  <title>Hedspi Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'static_pages', 'data-turbolinks-track': 'reload' %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
    <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <span class="navbar-brand"><%= link_to "Hedspi Blog", '/'  %></span>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Raking", blog_rakings_path, :class => 'navbar-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "My Blog", blogs_path, :class => 'navbar-link' %> 
            </li>
            <li class="nav-item">
              <%= link_to current_user.name, users_show_path(current_user), :class => 'navbar-link' %> 
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            <li>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %>
            <li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Hedspi Blog</h1>
            <span class="subheading">A Blog by Team 7</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <%= yield %>
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>
</body>
<html>

app/views/static_pages/home.html.erb
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      <% Blog.all.each do |blog| %>
        <div class="post-preview">
          <%= link_to blog do %>
            <h2 class="post-title">
              <%= blog.title%>
            </h2>
          <% end %>
          <p class ="post-meta">
            Posted by <%= blog.user.email %>
            on <%= blog.created_at %>
          </p>
        </div>
      <% end %>
        <hr>
      </div>
    </div>
  </div>

  

app/views/users/show.html.erb
<h1>Users Profile</h1>

<span><strong>Name: </strong><%= current_user.name %></span><br/>

<span><strong>Age: </strong><%= current_user.age %></span><br/>

<span><strong>Birthday: </strong><%= current_user.birthday %></span><br/>

<h3>Avatar: </h3>
<p>
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar %>
  <% end %>
</p>

<span><strong>Email: </strong><%= current_user.email %></span><br/>
<p>
  <%= link_to "Home", root_path %> ||
  <%= link_to "Edit", edit_user_registration_path %>
</p>
  